name: Lint
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "**/*.ts"
      - .github/workflows/lint.yml
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - .github/workflows/lint.yml
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install-nodejs
        name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - id: install-dependencies
        name: Install Dependencies
        run: yarn install --frozen-lockfile
      - id: generate-eslint-report
        name: Generate ESLint Report
        continue-on-error: true
        run: yarn lint:report
      - id: annotate-with-eslint
        name: Annotate with ESLint Report
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: ${{ github.workspace }}/eslint_report.json
      - id: upload-report
        name: Upload ESLint Report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: ${{ github.workspace }}/eslint_report.json
